### ISSUE TITLE
Format not getting, appended to id

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Router#9]
Possible bug

When there is 

```
$map->add(null, '/{:controller}/{:action}/{:id}');
```

Or 

```
$map->add('named_route', '/{:controller}/{:action}/{:id}');
```

in-front of the route 

```
$map->add('read', '/blog/read/{:id}{:format}', [
    'params' => [
        'id' => '(\d+)',
        'format' => '(\.json|\.html)?',
    ],
    'values' => [
        'controller' => 'blog',
        'action' => 'read',
        'format' => '.html',
    ]
]);
```

And when a request for a get `http://localhost:8000/blog/read/1.json` format not recognized 

```
Array ( [controller] => blog [action] => read [id] => 1.json )
```

But when 

```
$map->add(null, '/{:controller}/{:action}/{:id}');
```

Or 

```
$map->add('named_route', '/{:controller}/{:action}/{:id}');
```

is below the route 

```
$map->add('read', '/blog/read/{:id}{:format}', [
    'params' => [
        'id' => '(\d+)',
        'format' => '(\.json|\.html)?',
    ],
    'values' => [
        'controller' => 'blog',
        'action' => 'read',
        'format' => '.html',
    ]
]);
```

It works

```
Array ( [controller] => blog [action] => read [format] => .json [id] => 1 )
```

**Comment by pmjones** [comment]
This is the correct behavior, but I can see why it's unintuitive.  If you use `{:id}` and don't define its format, it gets a default format. The default format is "any character except a slash".  The string `"1.json"` matches that, and so the route matches.  You would need define a format for `{:id}`, either inline or with a `'format'` key; e.g., `{:id:(\d+)}`.

It looks like your example above is taken directly from the readme, which of course won't work the way you'd expect.  We'll have to change the readme so that it's actually a good example.

Thanks for pointing this out.
